language: node_js
node_js:
- node
- lts/*
cache:
  directories:
  - "~/.npm"
before_script:
- npm install -g npm@latest
script:
- npm ci
- npx jest --ci

env:
  # Github development key
  - secure: "f58gzQx1zz7YAfzbGEu/eefeND2CDlqDGy1GRFIOfniRcvnI30IZ08Q7uEwbrJIkuT2rdAp/Dv/xIfIjHc8fKSIpqI7O/8rmy9Gtt04e0eCoBudNRxYmIMdrU9cCh6936Ed8QY0Q8YdhtT9aIFQ1BDrnojGh0dYHMvKaBFkG8nK/u87LQLTIzFSNCB4+7HnhTv7x8iXzSWRjwCW0CO4ThmsWWQpwExwF/Vc1wrwhhnm3UST1Ztg50pQfquk0DbpSq1dVePbBkcJGReZtgztEweRt8mby3UaDMQFsYNikxiqM/63sYB3BPHBThdxkrznr0r/DjkY5I8JyPUrLNqTRPCz2b7OcuQYGEviRscn4LirbZpSy1GrRYJdWQ4xUPSZX3Cs/QW5Dv4AW3iJRAHTvTcJv+MnYJgqju3oeGp4ypoEvmuoDBF3V88/Yny+eGVVWxzFfFBaQOejJq/yzY3rxyOvYX4Bo2vpUa58kTbgsYxHFwot2toPI26drKhL/jrlyH09Bw43VjblHfHXmYyhAAFmfnHlfJiqQmPBF7ZRuvXNAyg4ueqpxM7kMGFctUb0fzBngaQwB3bsXfNPJCM0ReGXezU9psGlO6QtRQETnLRtBs/0yBrgwH9Pd37w/M5GcFwad0gbSOGrnVKhANMhfDIW9CkvX2hHKZTgEb/NoT6w="

notifications:
  slack:
    secure: EMwJfVf2J5G15+gb8zwjIrZrfDGdR865WoHys36Pk7D2YXwmirC5KRrpbj6m+wnQj/jtnx6DT5MaJkQp+i9LsKaOqJuRvtbED8v8Bgc8/vwWKV2+M5G0ZU3pXf63I7Sd2O2MjsL1strR2J5Djy6wZkntyeV3FgocuWmNEDXMkevTFOgi4z+SxyvHeck6hTStCteuNIf/RZ6uWPGo9qoKBWRcYZ+usUgY2DlGZ124n4O1sZJihXaUeLKCkfd321QtS0OnbL1L8QvyMloxhqPA44g486Y30q4imPvskwIHYyzByyaiF/Po2LAzJSdL9ZuwRuDRNd8NpCMd294FTctki3iwQoqIrf72siIYdJWoDW6PkYaT/5KBJdoTxlrRz3ARGSlTtdxovYlu9zLIl36IQpf4kvjzWzbulgK69hiPYNGDwsFtFBvT6iiezHfSGVCw+xjYjkiLX9h8lI9xd9y3yXJgLaLHzbep/KYEz2hjIVxHnqSlA/8ewiFPdmXJlRnpNpIznVvqtLDYRzdK1X/a6pMwJRXF8hpoGbPiGOC8ugtu/sB02E4EOukYmsZOv14KAAwLLOG0Om/4BXfuHXCl5c1Yakja0NwnhaoD4ZrmN7oouRJOI8Mvqf56AmGPm/sldhcf6LL2cvLc4NET8mMiIicIRbbCJ6xjE6tHTazMIFA=
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^devops/' BRANCH_TO_MERGE_INTO=dev GITHUB_REPO=cdown/srt /tmp/travis-automerge"